version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "network.publish_host=0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
        POSTGRES_DB: guillotina
        POSTGRES_PASSWORD: secret
        POSTGRES_USER: guillotina
    ports:
    - 5432:5432
  guillotina:
    image: plone/guillotina_cms:master
    command: sh -c "sleep 5 && g -c /usr/src/app/config.yaml"
    ports:
    - "8081:8081"
    links:
     - postgres
     - redis
     - elasticsearch
    volumes:
      - ${PWD}/local/config.yaml:/usr/src/app/config.yaml
  jupyter:
    image: guillotina/guillotina_notebook:latest
    ports:
    - "8888:8888"
    - "6006:6006"
    links:
     - postgres
     - redis
     - elasticsearch
    volumes:
      - ${PWD}/local/config.yaml:/app/config.yaml
      - ${PWD}/notebooks:/app/notebooks
      - ${PWD}/raw_data:/app/raw_data
      - ${PWD}/guillotina_processing:/usr/src/app
